# Site Settings
title                    : "A Father-Son, 12,000 Mile EV Road Trip Across the USA"
description              : foo
remote_theme             : pages-themes/cayman

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
