# Site Settings
remote_theme             : pages-themes/cayman@v0.2.0
title                    : A Father-Son, 12,000 Mile EV Road Trip Across the USA
description              : foo
locale                   : "en-US"

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
