# Site Settings
theme:                   : "cayman"
locale                   : "en-US"
title                    : "Father-Son Road Trip Across the US"
title_separator          : "-"
name                     : &name "Simon Wong"
description              : &description "experienced road tripper"
url                      : https://locborgtus.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/xcountry-roadtrip-2023" # the subpath of your site, e.g. "/blog"
repository               : ""
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
